### ISSUE TITLE
[feat] 포스트 작성기능

### ISSUE THREAD

**Issue by ollykingking** [saramdle/blog-team-four#11]
## Description

포스트를 작성하는 페이지(/write)에서 글을 작성하고 POST요청을 하여 backend와 통신함. 

## Todo

- [x] /write 페이지 디자인
- [x] /write 페이지 모바일 디자인
- [x] /write 페이지 사진 업로드 기능
- [x] POST요청 구현
- [x] 글쓰기 완료시 해당 포스트페이지(/posts/[postId])로 redirect
