### ISSUE TITLE
[feat] 생성, 수정시간을 자동으로 설정해주는 BaseTimeEntity 적용

### ISSUE THREAD

**Issue by an2z** [saramdle/blog-team-four#25]
## Description

도메인에 공통으로 들어가는 `createdAt`, `updatedAt` 필드의 중복을 줄이기 위해 JPA Auditing 기능을 활용한 BaseTimeEntity 클래스를 만들어 적용합니다.

## Todo

- [x] BaseTimeEntity 클래스 생성
- [x] Post 엔티티에 BaseTimeEntity 적용
- [x] Comment 엔티티에 BaseTimeEntity 적용

## ETC
JPA Auditing은 시간에 대해서 자동으로 값을 넣어주는 기능으로, 
트랜잭션 커밋 시점에 하이버네이트가 자동으로 시간 값을 채워 데이터베이스의 테이블에 넣어줍니다.
