### ISSUE TITLE
[chore] 의존성 및 DB 연동과 JPA 관련 설정 정보 추가

### ISSUE THREAD

**Issue by an2z** [saramdle/blog-team-four#3]
## Description

`build.gradle`, `application.yml` 파일은 충돌 위험이 있기 때문에 개발 진행에 공통적으로 필요한 설정을 추가합니다.

## Todo

- [x] JPA 의존성 추가
- [x] H2 데이터베이스 의존성 추가
- [x] MySQL 데이터베이스 의존성 추가
- [x] H2 데이터베이스 연동
- [x] JPA 관련 옵션 추가
