### ISSUE TITLE
[refactor] 기존 author 필드를 회원 엔티티로 변경 및 연관관계 적용

### ISSUE THREAD

**Issue by an2z** [saramdle/blog-team-four#47]
## Description

기존에는 author(작성자)라는 필드를 String 타입으로 넣어주는 방식이었지만, 
`User` 엔티티가 추가됨에 따라 `User-Post`, `User-Comment` 간 연관관계를 매핑하는 방식으로 변경합니다.

## Todo

- [x] `Post`에서 author 필드를 사용하는 코드들을 모두 user로 변경
- [x] `User`에서 author 필드를 사용하는 코드들을 모두 user로 변경
- [x] `Post`-`User` 간 `@ManyToOne` 단방향 연관관계 매핑
- [x] `Comment`-`User` 간 `@ManyToOne` 단방향 연관관계 매핑
